# Generated by Django 5.0.3 on 2024-06-19 03:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profession_name', models.CharField(max_length=50, unique=True)),
                ('no_need_approval', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('reporterName', models.CharField(max_length=255)),
                ('datetime', models.CharField(max_length=255, null=True)),
                ('operationLineNumber', models.CharField(max_length=255)),
                ('machineNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('problemDescription', models.TextField()),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Validated'), ('3', 'Sent'), ('4', 'Solved'), ('5', 'Finished'), ('6', 'Rejected')], default='0', max_length=1)),
                ('confirmedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('sentBy', models.CharField(blank=True, max_length=255, null=True)),
                ('sentTo', models.CharField(blank=True, max_length=255, null=True)),
                ('solvedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('rejectedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('problemCategory', models.CharField(max_length=255, null=True)),
                ('subCategory', models.CharField(max_length=255, null=True)),
                ('subCategoryForUser', models.CharField(max_length=255, null=True)),
                ('emailNotifyDate', models.CharField(blank=True, max_length=255, null=True)),
                ('dueDate', models.CharField(blank=True, max_length=255, null=True)),
                ('finishDate', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subCategory', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryForUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subCategoryForUser', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_line_no', models.ManyToManyField(blank=True, to='inform.operationline')),
                ('profession', models.ManyToManyField(blank=True, to='inform.profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageData', models.ImageField(blank=True, null=True, upload_to='reportImages/')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inform.report')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solutionID', models.AutoField(primary_key=True, serialize=False)),
                ('solverName', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('datetime', models.CharField(max_length=255, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inform.report')),
            ],
            options={
                'db_table': 'solution',
            },
        ),
        migrations.CreateModel(
            name='ImageSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageData', models.ImageField(blank=True, null=True, upload_to='solutionImages/')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inform.solution')),
            ],
            options={
                'db_table': 'image_solution',
            },
        ),
        migrations.AddField(
            model_name='profession',
            name='subCategory',
            field=models.ManyToManyField(blank=True, to='inform.subcategory'),
        ),
        migrations.AddField(
            model_name='profession',
            name='subCategoryForUser',
            field=models.ManyToManyField(blank=True, to='inform.subcategoryforuser'),
        ),
    ]
