# Generated by Django 5.0.6 on 2024-06-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='no_need_approval',
            field=models.BooleanField(default=False),
        ),
    ]
