# Generated by Django 5.0.6 on 2024-06-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_report_rank_alter_profession_no_need_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='no_need_approval_chief',
            field=models.BooleanField(default=False),
        ),
    ]
