# Generated by Django 5.0.6 on 2024-06-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0003_profession_no_need_approval_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporterNameReal',
            field=models.CharField(default='Piak', max_length=255),
            preserve_default=False,
        ),
    ]
